version: 2
jobs:
  build:
    working_directory: ~/cyphondock
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: Install docker-compose
          command: |
            pip install -U docker-compose
      - run:
          name: Build Docker containers
          command: |
            docker-compose -f docker-compose.travis.yml \
            up --build -d
      - run:
          name: Wait for containers to boot up
          command: sleep 30
      - run:
          name: Run tests
          command: ./scripts/runtests.sh
